version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: coworking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: